import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/app/components/main-nav/MainNav";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Special file to render a component that is common on all pages like Navigation.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  const App = (
    <>
      <MainNav />
      <div className="appContainer">{children}</div>
    </>
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {App}
        </Providers>
      </body>
    </html>
  );
}
